# Generated by Django 2.2 on 2019-04-11 00:12

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('documenttype', models.CharField(max_length=100)),
                ('title', django_mysql.models.JSONField(default=dict)),
                ('introduction', django_mysql.models.JSONField(default=dict)),
                ('abstract', django_mysql.models.JSONField(default=dict)),
                ('literaturereview', django_mysql.models.JSONField(default=dict)),
                ('conclusion', django_mysql.models.JSONField(default=dict)),
                ('references', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
            },
        ),
    ]
