# Generated by Django 2.2 on 2019-04-11 00:13

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='references',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
