# Generated by Django 2.2 on 2019-04-12 12:30

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_auto_20190411_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='otherFields',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='template',
            name='slug',
            field=models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
