# Generated by Django 2.2 on 2019-04-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_auto_20190412_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='abstract',
            new_name='documentfieldsitems',
        ),
        migrations.RemoveField(
            model_name='template',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='template',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='template',
            name='literaturereview',
        ),
        migrations.RemoveField(
            model_name='template',
            name='otherFields',
        ),
        migrations.RemoveField(
            model_name='template',
            name='references',
        ),
    ]
